### ISSUE TITLE
Мойка полов и мелкие ошибки, предложения

### ISSUE THREAD

**Issue by Enzokot** [sergeylysov/sst_cloud#4]
Добрый день.
Огромное спасибо за долгожданную интеграцию! 🎉🎉🎉
Есть несколько вопросов, ошибок, предложений:
1. Предлагаю добавить `switch` для режима `мойка пола`
2. Если имеется два и наверно более контроллера протечки, то при добавлении возникает коллизия присвоения имен и НА не позволяет их создать.
<details><summary>Ошибки</summary>

``
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_1_leakSensorAlert already exists - ignoring binary_sensor.leaksensor_line_1
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_2_leakSensorAlert already exists - ignoring binary_sensor.leaksensor_line_2
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_3_leakSensorAlert already exists - ignoring binary_sensor.leaksensor_line_3
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_4_leakSensorAlert already exists - ignoring binary_sensor.leaksensor_line_4
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_1_leakSensorAlert is already used by binary_sensor.leaksensor_line_1 - ignoring binary_sensor.leaksensor_line_1
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_2_leakSensorAlert is already used by binary_sensor.leaksensor_line_2 - ignoring binary_sensor.leaksensor_line_2
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_3_leakSensorAlert is already used by binary_sensor.leaksensor_line_3 - ignoring binary_sensor.leaksensor_line_3
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform sst_cloud does not generate unique IDs. ID line_4_leakSensorAlert is already used by binary_sensor.leaksensor_line_4 - ignoring binary_sensor.leaksensor_line_4
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform sst_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.neptun_sanuzel cannot be added a second time to an entity platform
2022-05-11 16:55:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up sst_cloud platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.neptun_sanuzel cannot be added a second time to an entity platform
``

</details>

3. Если у какого-то канала выбран режим `счетчика` то для него будет создан `sensor` с потреблением воды? (если да, то как поведет себя компонент, если пользователь изменит тип канала, после того как контроллер добавлен в НА?) У меня пока счетчики не подключены, не смог проверить.
4. Не успел понять причин, но появились уведомления о превышении времени ожидания обновления сенсоров/переключателей,  возможно из за п.2
<details><summary>Предупреждения</summary>

``
2022-05-11 16:56:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.neptun_sanuzel is taking over 10 seconds
2022-05-11 16:57:03 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating sst_cloud binary_sensor took longer than the scheduled update interval 0:00:30
2022-05-11 16:57:33 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating sst_cloud binary_sensor took longer than the scheduled update interval 0:00:30
2022-05-11 16:58:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.neptun_sanuzel is taking over 10 seconds
2022-05-11 16:59:03 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating sst_cloud binary_sensor took longer than the scheduled update interval 0:00:30
2022-05-11 17:01:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.neptun_sanuzel is taking over 10 seconds
``

</details>

**Comment by sergeylysov** [comment]
Добрый день!
1. Добавлю, как добавлю, отпишусь здесь.
2. Понял проблему, в ближайшее время постараюсь исправить
3. Да, сенсор с потреблением воды будет создан после перезапуска интеграции, в случае Neptun Prow+ WiFi, когда счетчик подключается вместо датчика, то останется датчик, но работать естественно не будет.
4. это из-за того что облако SST работает не очень стабильно и не очень быстро.

**Comment by Enzokot** [comment]
Добрый день!
3. я правильно понял, если в настройках канала Neptun Prow+ WiFi произвести изменение, то чтобы отразить в НА, нужно передабавить контроллер?
4. т.е. со стороны интеграции "обыграть" не получится эти проблемы облака?

Еще раз хотелось бы поблагодарить за труды и интеграцию. Спасибо большое!

**Comment by sergeylysov** [comment]
3. передобавлять не нужно, достаточно перезагрузить саму интеграцию или просто весь HA
4. Думаю нет, предупреждения в логах все равно будут из-за долгих запросов

**Comment by Enzokot** [comment]
4. получается даже один запрос с заведомо полученным токеном выполняется более 10-30сек?

**Comment by sergeylysov** [comment]
да, HA похоже ругается на все долгие запросы

**Comment by sergeylysov** [comment]
Опубликовал новую версию 0.1.5, попробуйте обновиться, добавил переключатель для мойки пола и проблема с датчиками должна пройти, но нужно переконфигурировать итеграцию

**Comment by Enzokot** [comment]
Обновился. Интеграция из конфигурации ранее была удалена. Добавил заново, но после добавления по каким то причинам все равно была ошибка (хотя, насколько я понимаю, все добавлено успешно):
`2022-05-12 17:07:54 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform sst_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.neptun_sanuzel cannot be added a second time to an entity platform
2022-05-12 17:07:55 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up sst_cloud platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.neptun_sanuzel cannot be added a second time to an entity platform`

по п.4, на версии компонента 0.1.5 почему то предупреждения только по одному бинарнику (судя по всему он как раз в ошибке конфигурирования)
``
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:746
First occurred: 17:11:04 (3 occurrences)
Last logged: 17:15:04
Update of binary_sensor.neptun_sanuzel is taking over 10 seconds
``
и
``
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:746
First occurred: 17:11:04 (3 occurrences)
Last logged: 17:15:04
Update of binary_sensor.neptun_sanuzel is taking over 10 seconds
``

5. В качестве предложения, в api правда не смог найти, но в web версии есть, добавить версию прошивку контроллера
![image](https://user-images.githubusercontent.com/43236573/168097605-f04708a5-ac58-4770-a5a7-e0e721c17549.png)

**Comment by sergeylysov** [comment]
Все равно не удается отловить проблему, напишите мне в телеграм пожалуйста https://t.me/s_lysov
По поводу имени идея хорошая, но в апи крайне неудобно это размещено, может сделаю позже (лучше завести отдельный issue) для счетчика кстати прокидывается нормальное имя.
